service: dnd-9th-msa-api

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, self:custom.defaultStage}
  region: ${opt:region, self:custom.defaultRegion}
  stackName: ${self:service}-${self:provider.stage}
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    REGION_ABBR: ${self:custom.regionAbbr.${self:provider.region}}
  profile: ${self:custom.profiles.${self:provider.stage}}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:*"
      Resource: "*"
custom:
  defaultStage: dev
  defaultRegion: ap-northeast-2
  regionAbbr:
    ap-northeast-2: an2
  apiKeys:
    dev:
      - name: ""
    prod:
      - name: ""
  profiles:
    dev: ""
    prod: ""
  domain:
    dev: ""
    prod: ""
  certName:
    dev: ""
    prod: ""
  customDomain:
    certificateName: ${self:custom.certName.${opt:stage}}
    domainName: ${self:custom.domain.${opt:stage}}
    basePath: ''
    securityPolicy: tls_1_2
    apiType: rest
    autoDomain: false
    stage: ${self:provider.stage}
    createRoute53Record: false

functions:
  plantTest:
    handler: plant/test.handler
    events:
      - http:
          path: plant
          method: get
          cors: true
          private: true
          headers:
            - x-api-key
          allowCredentials: true
package:
  individually: true
  exclude:
    - node_modules/**
    - "*.ts"
